"""user table minor update

Revision ID: da041b91ccc4
Revises: f0d695605997
Create Date: 2025-07-21 01:30:37.988379

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'da041b91ccc4'
down_revision: Union[str, Sequence[str], None] = 'f0d695605997'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.VARCHAR(),
               type_=sa.TIMESTAMP(),
               existing_nullable=False,
               server_default=sa.text('CURRENT_TIMESTAMP'),
                postgresql_using="created_at::timestamp without time zone")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
